version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: bossdb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bossnet

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      - DB_HOST=mongo
      - DB_USER=admin
      - DB_PASS=secret
      - DB_NAME=bossdb
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "4000:4000"
    networks:
      - bossnet

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - bossnet

volumes:
  mongo-data:

networks:
  bossnet:
