version: "3.9"
services:
  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - devnet

  server:
    build: ./server
    environment:
      - DB_HOST=mongo
      - DB_USER=admin
      - DB_PASS=secret
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - devnet

networks:
  devnet:
